wandb_version: 1

project_name:
  desc: null
  value: DLA_Lab1_CNN
save_model:
  desc: null
  value: false
save_artifact:
  desc: null
  value: false
dataset:
  desc: null
  value: MNIST
convnet:
  desc: null
  value: false
residual:
  desc: null
  value: false
resnet:
  desc: null
  value: false
fullycnn:
  desc: null
  value: false
cam:
  desc: null
  value: false
MLP_hidden_size:
  desc: null
  value:
  - 256
  - 128
  - 128
CNN_hidden_size:
  desc: null
  value:
  - 64
depth:
  desc: null
  value: 1
kernel_size:
  desc: null
  value: 3
stride:
  desc: null
  value: 1
padding:
  desc: null
  value: 1
pool_size:
  desc: null
  value: 2
pool:
  desc: null
  value: false
use_bn:
  desc: null
  value: true
resnet_name:
  desc: null
  value: 18
resnet_hidden_size:
  desc: null
  value:
  - 64
  - 128
  - 256
  - 512
batch_size:
  desc: null
  value: 1024
epochs:
  desc: null
  value: 20
activation:
  desc: null
  value: ReLU
optimizer:
  desc: null
  value: Adam
learning_rate:
  desc: null
  value: 0.0001
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.0001
dropout:
  desc: null
  value: 0.1
log_interval:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706565154.801189
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.10.9
      5: 0.16.1
      6: 4.24.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
