# Setting Run Configuration
project_name: DLA_Lab1_CNN

# Saving settings
save_model: True
save_artifact: False

# Dataset settings
dataset: MNIST

# Model settings
convnet: False
residual: False
resnet: False

fullycnn: False
cam: False

# MLP settings
MLP_hidden_size: [128, 64]

# ConvNet settings
CNN_hidden_size: [64]                               # Size of the convolutional layers: for ResidualCNN, only the first value is used
depth: 1                                            # Number of convolutional layers
kernel_size: 3
stride: 1
padding: 1
pool_size: 2
pool: False                                         # Whether to use MaxPool or not
use_bn: True                                        # Whether to use Batch Normalization or not

# ResNet settings
resnet_name: 18                                     # ResNet architecture: [9, 18, 34, 50, 101, 152]
resnet_hidden_size: [64, 128, 256, 512]             # Number of filters for each convolutional block (4 blocks)

# Training loop settings
batch_size: 2048
epochs: 10

# Loss & Optimizer settings
activation: ReLU                                    # Activation function
optimizer: Adam                                     # Optimizer: [Adam, SGD, RMSprop]
learning_rate: !!float 5e-4
momentum: 0.9
weight_decay: !!float 1e-4
dropout: 0.3

# Log settings
log_interval: 10                                    # Interval between logs, expressed in number of batches