# Deep Learning Applications 2023 course, held by Professor Andrew David Bagdanov - University of Florence, Italy
# Created by Giovanni Colombo - Mat. 7092745
# Dedicated Repository on GitHub at https://github.com/giovancombo/DLA_Labs/tree/main/lab1

# Dataset settings
dataset: CIFAR10

# Model hyperparameters
convnet: True
residual: False
resnet: False

depth: 5
MLP_hidden_size: [128]                        # PROVA diverse depth
CNN_hidden_size: [64]                         # Size of Conv layers: for ResidualCNN, only value at idx 0 is used
resnet_name: 18                               # ResNet architecture: [9, 18, 34, 50, 101, 152] available
resnet_hidden_size: [64, 128, 256, 512]       # Number of filters for each convolutional block (4 blocks)

# Training loop hyperparameters
batch_size: 128
epochs: 3
num_workers: 4
learning_rate: !!float 1e-4
weight_decay: !!float 1e-4
dropout: 0.2
gamma: 0.9                                    # Learning rate decay factor

# Log settings
log_freq: 10                                  # Interval between logs, expressed in number of batches
